all: libclient.a libserver.a

libserver.a:
	$(MAKE) -C dlls -f Makefile.switch

libclient.a:
	$(MAKE) -C cl_dll -f Makefile.switch

clean:
	$(MAKE) -C cl_dll -f Makefile.switch clean
	$(MAKE) -C dlls -f Makefile.switch clean