#include "switch_defs.h"
#include "extdll.h"
#include "util.h"
#include "cbase.h"

extern "C"
{

void GiveFnptrsToDll( enginefuncs_t *pengfuncsFromEngine, globalvars_t *pGlobals );
int GetEntityAPI( DLL_FUNCTIONS *pFunctionTable, int interfaceVersion );
int GetEntityAPI2( DLL_FUNCTIONS *pFunctionTable, int *interfaceVersion );
int Server_GetPhysicsInterface( int iVersion, server_physics_api_t *pfuncsFromEngine, physics_interface_t *pFunctionTable );

// Autogenerated functions
void info_displacer_xen_target( entvars_t *pev );
void monster_cine_barney( entvars_t *pev );
void xen_hair( entvars_t *pev );
void monster_barney_dead( entvars_t *pev );
void game_zone_player( entvars_t *pev );
void func_conveyor( entvars_t *pev );
void game_counter( entvars_t *pev );
void nihilanth_energy_ball( entvars_t *pev );
void env_render( entvars_t *pev );
void monster_sitting_scientist( entvars_t *pev );
void weaponbox( entvars_t *pev );
void game_score( entvars_t *pev );
void weapon_gauss( entvars_t *pev );
void func_notepad( entvars_t *pev );
void light( entvars_t *pev );
void info_flaghelper( entvars_t *pev );
void env_rtcamera( entvars_t *pev );
void weapon_crossbow( entvars_t *pev );
void info_node_air( entvars_t *pev );
void func_button( entvars_t *pev );
void trigger_counter( entvars_t *pev );
void func_rot_button( entvars_t *pev );
void trigger( entvars_t *pev );
void bodyque( entvars_t *pev );
void info_emittertarget( entvars_t *pev );
void func_door_rotating( entvars_t *pev );
void ammo_glockclip( entvars_t *pev );
void garg_stomp( entvars_t *pev );
void monster_satchel( entvars_t *pev );
void monster_tentacle( entvars_t *pev );
void monstermaker( entvars_t *pev );
void weapon_handgrenade( entvars_t *pev );
void info_intermission( entvars_t *pev );
void trigger_changelevel( entvars_t *pev );
void env_lightning( entvars_t *pev );
void trigger_bit( entvars_t *pev );
void func_frame( entvars_t *pev );
void monster_miniturret( entvars_t *pev );
void info_teleport_destination( entvars_t *pev );
void gibshooter( entvars_t *pev );
void item_airtank( entvars_t *pev );
void monster_human_assassin( entvars_t *pev );
void func_pendulum( entvars_t *pev );
void func_trackautochange( entvars_t *pev );
void monster_cine_scientist( entvars_t *pev );
void streak_spiral( entvars_t *pev );
void monster_cine2_scientist( entvars_t *pev );
void monster_cine3_barney( entvars_t *pev );
void env_global( entvars_t *pev );
void func_rotating( entvars_t *pev );
void monster_hgrunt_dead( entvars_t *pev );
void cycler_wreckage( entvars_t *pev );
void func_pushable( entvars_t *pev );
void cycler( entvars_t *pev );
void game_end( entvars_t *pev );
void xen_spore_medium( entvars_t *pev );
void monster_bigmomma( entvars_t *pev );
void monster_rat( entvars_t *pev );
void trigger_teleport( entvars_t *pev );
void weapon_displacer( entvars_t *pev );
void xen_tree( entvars_t *pev );
void monster_nihilanth( entvars_t *pev );
void monster_flyer( entvars_t *pev );
void trigger_hurt( entvars_t *pev );
void info_player_deathmatch( entvars_t *pev );
void monster_cine2_slave( entvars_t *pev );
void monster_bloater( entvars_t *pev );
void test_effect( entvars_t *pev );
void hvr_rocket( entvars_t *pev );
void env_dlight( entvars_t *pev );
void func_tankmortar( entvars_t *pev );
void env_lensflare( entvars_t *pev );
void game_counter_set( entvars_t *pev );
void monster_gargantua( entvars_t *pev );
void effect_warpball( entvars_t *pev );
void info_bigmomma( entvars_t *pev );
void weapon_egon( entvars_t *pev );
void monster_vortigaunt( entvars_t *pev );
void monster_scientist( entvars_t *pev );
void weapon_9mmAR( entvars_t *pev );
void monster_barney( entvars_t *pev );
void monster_bullchicken( entvars_t *pev );
void weapon_rpg( entvars_t *pev );
void momentary_door( entvars_t *pev );
void func_plat( entvars_t *pev );
void trigger_kicker( entvars_t *pev );
void item_healthcharger( entvars_t *pev );
void monster_generic( entvars_t *pev );
void func_healthcharger( entvars_t *pev );
void bot( entvars_t *pev );
void monster_flyer_flock( entvars_t *pev );
void monster_alien_controller( entvars_t *pev );
void trigger_monsterjump( entvars_t *pev );
void trigger_camera( entvars_t *pev );
void ammo_buckshot( entvars_t *pev );
void spark_shower( entvars_t *pev );
void weapon_tripmine( entvars_t *pev );
void light_spot( entvars_t *pev );
void env_fade( entvars_t *pev );
void testhull( entvars_t *pev );
void env_sound( entvars_t *pev );
void func_platrot( entvars_t *pev );
void env_message( entvars_t *pev );
void worldspawn( entvars_t *pev );
void env_debris( entvars_t *pev );
void trigger_gravity( entvars_t *pev );
void env_funnel( entvars_t *pev );
void monster_alien_slave( entvars_t *pev );
void func_trackchange( entvars_t *pev );
void bmortar( entvars_t *pev );
void DelayedUse( entvars_t *pev );
void monster_furniture( entvars_t *pev );
void monster_gman( entvars_t *pev );
void env_model( entvars_t *pev );
void game_player_equip( entvars_t *pev );
void env_bubbles( entvars_t *pev );
void game_team_set( entvars_t *pev );
void node_viewer( entvars_t *pev );
void trigger_autosave( entvars_t *pev );
void trigger_changetarget( entvars_t *pev );
void entity_botcam( entvars_t *pev );
void monster_houndeye( entvars_t *pev );
void controller_head_ball( entvars_t *pev );
void item_slave_collar( entvars_t *pev );
void env_explosion( entvars_t *pev );
void xen_ttrigger( entvars_t *pev );
void path_track( entvars_t *pev );
void func_wall_toggle( entvars_t *pev );
void momentary_rot_button( entvars_t *pev );
void trigger_clientspawn( entvars_t *pev );
void node_viewer_human( entvars_t *pev );
void func_tracktrain( entvars_t *pev );
void controller_energy_ball( entvars_t *pev );
void monster_zombie( entvars_t *pev );
void monster_barnacle( entvars_t *pev );
void env_warpball( entvars_t *pev );
void trigger_multiple( entvars_t *pev );
void ammo_egonclip( entvars_t *pev );
void trigger_endsection( entvars_t *pev );
void displacer_teleporter( entvars_t *pev );
void func_friction( entvars_t *pev );
void xen_hull( entvars_t *pev );
void env_spark( entvars_t *pev );
void env_smoker( entvars_t *pev );
void env_glow( entvars_t *pev );
void player( entvars_t *pev );
void target_cdaudio( entvars_t *pev );
void trigger_push( entvars_t *pev );
void game_team_master( entvars_t *pev );
void scripted_sentence( entvars_t *pev );
void laser_spot( entvars_t *pev );
void xen_spore_small( entvars_t *pev );
void monster_cockroach( entvars_t *pev );
void monster_tentaclemaw( entvars_t *pev );
void path_corner( entvars_t *pev );
void game_player_team( entvars_t *pev );
void func_mortar_field( entvars_t *pev );
void ammo_rpgclip( entvars_t *pev );
void info_displacer_earthdeastination( entvars_t *pev );
void func_tank( entvars_t *pev );
void func_tanklaser( entvars_t *pev );
void node_viewer_large( entvars_t *pev );
void info_landmark( entvars_t *pev );
void monster_ichthyosaur( entvars_t *pev );
void info_node( entvars_t *pev );
void func_illusionary( entvars_t *pev );
void trigger_new_hurt( entvars_t *pev );
void item_sodacan( entvars_t *pev );
void ammo_357( entvars_t *pev );
void item_longjump( entvars_t *pev );
void squidspit( entvars_t *pev );
void ammo_mp5grenades( entvars_t *pev );
void info_cheathelper( entvars_t *pev );
void ammo_crossbow( entvars_t *pev );
void env_sprite( entvars_t *pev );
void item_antidote( entvars_t *pev );
void func_water( entvars_t *pev );
void item_suit( entvars_t *pev );
void xen_spore_large( entvars_t *pev );
void monster_mortar( entvars_t *pev );
void func_tankrocket( entvars_t *pev );
void node_viewer_fly( entvars_t *pev );
void info_target( entvars_t *pev );
void info_null( entvars_t *pev );
void func_breakable( entvars_t *pev );
void monster_hevsuit_dead( entvars_t *pev );
void monster_headcrab( entvars_t *pev );
void func_wall( entvars_t *pev );
void trigger_random( entvars_t *pev );
void trigger_autobot( entvars_t *pev );
void infodecal( entvars_t *pev );
void func_monsterclip( entvars_t *pev );
void cycler_sprite( entvars_t *pev );
void weapon_python( entvars_t *pev );
void monster_tripmine( entvars_t *pev );
void monster_human_grunt( entvars_t *pev );
void func_guntarget( entvars_t *pev );
void env_elight( entvars_t *pev );
void trigger_auto( entvars_t *pev );
void hornet( entvars_t *pev );
void func_door( entvars_t *pev );
void scripted_sequence( entvars_t *pev );
void trigger_enddecay( entvars_t *pev );
void world_items( entvars_t *pev );
void weapon_shotgun( entvars_t *pev );
void ammo_gaussclip( entvars_t *pev );
void item_healthkit( entvars_t *pev );
void ammo_mp5clip( entvars_t *pev );
void speaker( entvars_t *pev );
void ambient_generic( entvars_t *pev );
void func_recharge( entvars_t *pev );
void weapon_satchel( entvars_t *pev );
void button_target( entvars_t *pev );
void trigger_playerfreeze( entvars_t *pev );
void func_tankcontrols( entvars_t *pev );
void aiscripted_sequence( entvars_t *pev );
void monster_sentry( entvars_t *pev );
void weapon_9mmhandgun( entvars_t *pev );
void monster_apache( entvars_t *pev );
void trigger_once( entvars_t *pev );
void monster_cine2_hvyweapons( entvars_t *pev );
void ammo_9mmAR( entvars_t *pev );
void monster_alien_grunt( entvars_t *pev );
void weapon_357( entvars_t *pev );
void func_train( entvars_t *pev );
void monster_leech( entvars_t *pev );
void info_player_start( entvars_t *pev );
void env_blood( entvars_t *pev );
void crossbow_bolt( entvars_t *pev );
void trigger_relay( entvars_t *pev );
void env_laser( entvars_t *pev );
void multi_manager( entvars_t *pev );
void monster_babycrab( entvars_t *pev );
void env_beverage( entvars_t *pev );
void beam( entvars_t *pev );
void env_beam( entvars_t *pev );
void env_shooter( entvars_t *pev );
void monster_osprey( entvars_t *pev );
void light_environment( entvars_t *pev );
void xen_plantlight( entvars_t *pev );
void game_text( entvars_t *pev );
void rpg_rocket( entvars_t *pev );
void item_recharge( entvars_t *pev );
void player_loadsaved( entvars_t *pev );
void monster_turret( entvars_t *pev );
void multisource( entvars_t *pev );
void weapon_vorti( entvars_t *pev );
void weapon_hornetgun( entvars_t *pev );
void grenade( entvars_t *pev );
void env_lasermirror( entvars_t *pev );
void weapon_crowbar( entvars_t *pev );
void func_traincontrols( entvars_t *pev );
void player_weaponstrip( entvars_t *pev );
void monster_player( entvars_t *pev );
void monster_snark( entvars_t *pev );
void weapon_mp5( entvars_t *pev );
void weapon_snark( entvars_t *pev );
void monster_grunt_repel( entvars_t *pev );
void monster_cine3_scientist( entvars_t *pev );
void cine_blood( entvars_t *pev );
void item_eyescanner( entvars_t *pev );
void ammo_9mmclip( entvars_t *pev );
void trigger_transition( entvars_t *pev );
void fireanddie( entvars_t *pev );
void soundent( entvars_t *pev );
void cycler_prdroid( entvars_t *pev );
void cycler_weapon( entvars_t *pev );
void trigger_bit_counter( entvars_t *pev );
void trigger_cdaudio( entvars_t *pev );
void game_player_hurt( entvars_t *pev );
void item_battery( entvars_t *pev );
void env_shake( entvars_t *pev );
void monster_cine_panther( entvars_t *pev );
void ammo_ARgrenades( entvars_t *pev );
void item_security( entvars_t *pev );
void weapon_glock( entvars_t *pev );
void func_ladder( entvars_t *pev );
void monster_scientist_dead( entvars_t *pev );
void ammo_9mmbox( entvars_t *pev );
void trigger_lockedmission( entvars_t *pev );


dllexport_t switch_server_exports[] = {
	{ "GiveFnptrsToDll", (void*)GiveFnptrsToDll },
	{ "GetEntityAPI", (void*)GetEntityAPI },
	{ "GetEntityAPI2", (void*)GetEntityAPI2 },
	{ "Server_GetPhysicsInterface", (void*)Server_GetPhysicsInterface },
	
	// Autogenerated exports
	{ "info_displacer_xen_target", (void*)info_displacer_xen_target },
	{ "monster_cine_barney", (void*)monster_cine_barney },
	{ "xen_hair", (void*)xen_hair },
	{ "monster_barney_dead", (void*)monster_barney_dead },
	{ "game_zone_player", (void*)game_zone_player },
	{ "func_conveyor", (void*)func_conveyor },
	{ "game_counter", (void*)game_counter },
	{ "nihilanth_energy_ball", (void*)nihilanth_energy_ball },
	{ "env_render", (void*)env_render },
	{ "monster_sitting_scientist", (void*)monster_sitting_scientist },
	{ "weaponbox", (void*)weaponbox },
	{ "game_score", (void*)game_score },
	{ "weapon_gauss", (void*)weapon_gauss },
	{ "func_notepad", (void*)func_notepad },
	{ "light", (void*)light },
	{ "info_flaghelper", (void*)info_flaghelper },
	{ "env_rtcamera", (void*)env_rtcamera },
	{ "weapon_crossbow", (void*)weapon_crossbow },
	{ "info_node_air", (void*)info_node_air },
	{ "func_button", (void*)func_button },
	{ "trigger_counter", (void*)trigger_counter },
	{ "func_rot_button", (void*)func_rot_button },
	{ "trigger", (void*)trigger },
	{ "bodyque", (void*)bodyque },
	{ "info_emittertarget", (void*)info_emittertarget },
	{ "func_door_rotating", (void*)func_door_rotating },
	{ "ammo_glockclip", (void*)ammo_glockclip },
	{ "garg_stomp", (void*)garg_stomp },
	{ "monster_satchel", (void*)monster_satchel },
	{ "monster_tentacle", (void*)monster_tentacle },
	{ "monstermaker", (void*)monstermaker },
	{ "weapon_handgrenade", (void*)weapon_handgrenade },
	{ "info_intermission", (void*)info_intermission },
	{ "trigger_changelevel", (void*)trigger_changelevel },
	{ "env_lightning", (void*)env_lightning },
	{ "trigger_bit", (void*)trigger_bit },
	{ "func_frame", (void*)func_frame },
	{ "monster_miniturret", (void*)monster_miniturret },
	{ "info_teleport_destination", (void*)info_teleport_destination },
	{ "gibshooter", (void*)gibshooter },
	{ "item_airtank", (void*)item_airtank },
	{ "monster_human_assassin", (void*)monster_human_assassin },
	{ "func_pendulum", (void*)func_pendulum },
	{ "func_trackautochange", (void*)func_trackautochange },
	{ "monster_cine_scientist", (void*)monster_cine_scientist },
	{ "streak_spiral", (void*)streak_spiral },
	{ "monster_cine2_scientist", (void*)monster_cine2_scientist },
	{ "monster_cine3_barney", (void*)monster_cine3_barney },
	{ "env_global", (void*)env_global },
	{ "func_rotating", (void*)func_rotating },
	{ "monster_hgrunt_dead", (void*)monster_hgrunt_dead },
	{ "cycler_wreckage", (void*)cycler_wreckage },
	{ "func_pushable", (void*)func_pushable },
	{ "cycler", (void*)cycler },
	{ "game_end", (void*)game_end },
	{ "xen_spore_medium", (void*)xen_spore_medium },
	{ "monster_bigmomma", (void*)monster_bigmomma },
	{ "monster_rat", (void*)monster_rat },
	{ "trigger_teleport", (void*)trigger_teleport },
	{ "weapon_displacer", (void*)weapon_displacer },
	{ "xen_tree", (void*)xen_tree },
	{ "monster_nihilanth", (void*)monster_nihilanth },
	{ "monster_flyer", (void*)monster_flyer },
	{ "trigger_hurt", (void*)trigger_hurt },
	{ "info_player_deathmatch", (void*)info_player_deathmatch },
	{ "monster_cine2_slave", (void*)monster_cine2_slave },
	{ "monster_bloater", (void*)monster_bloater },
	{ "test_effect", (void*)test_effect },
	{ "hvr_rocket", (void*)hvr_rocket },
	{ "env_dlight", (void*)env_dlight },
	{ "func_tankmortar", (void*)func_tankmortar },
	{ "env_lensflare", (void*)env_lensflare },
	{ "game_counter_set", (void*)game_counter_set },
	{ "monster_gargantua", (void*)monster_gargantua },
	{ "effect_warpball", (void*)effect_warpball },
	{ "info_bigmomma", (void*)info_bigmomma },
	{ "weapon_egon", (void*)weapon_egon },
	{ "monster_vortigaunt", (void*)monster_vortigaunt },
	{ "monster_scientist", (void*)monster_scientist },
	{ "weapon_9mmAR", (void*)weapon_9mmAR },
	{ "monster_barney", (void*)monster_barney },
	{ "monster_bullchicken", (void*)monster_bullchicken },
	{ "weapon_rpg", (void*)weapon_rpg },
	{ "momentary_door", (void*)momentary_door },
	{ "func_plat", (void*)func_plat },
	{ "trigger_kicker", (void*)trigger_kicker },
	{ "item_healthcharger", (void*)item_healthcharger },
	{ "monster_generic", (void*)monster_generic },
	{ "func_healthcharger", (void*)func_healthcharger },
	{ "bot", (void*)bot },
	{ "monster_flyer_flock", (void*)monster_flyer_flock },
	{ "monster_alien_controller", (void*)monster_alien_controller },
	{ "trigger_monsterjump", (void*)trigger_monsterjump },
	{ "trigger_camera", (void*)trigger_camera },
	{ "ammo_buckshot", (void*)ammo_buckshot },
	{ "spark_shower", (void*)spark_shower },
	{ "weapon_tripmine", (void*)weapon_tripmine },
	{ "light_spot", (void*)light_spot },
	{ "env_fade", (void*)env_fade },
	{ "testhull", (void*)testhull },
	{ "env_sound", (void*)env_sound },
	{ "func_platrot", (void*)func_platrot },
	{ "env_message", (void*)env_message },
	{ "worldspawn", (void*)worldspawn },
	{ "env_debris", (void*)env_debris },
	{ "trigger_gravity", (void*)trigger_gravity },
	{ "env_funnel", (void*)env_funnel },
	{ "monster_alien_slave", (void*)monster_alien_slave },
	{ "func_trackchange", (void*)func_trackchange },
	{ "bmortar", (void*)bmortar },
	{ "DelayedUse", (void*)DelayedUse },
	{ "monster_furniture", (void*)monster_furniture },
	{ "monster_gman", (void*)monster_gman },
	{ "env_model", (void*)env_model },
	{ "game_player_equip", (void*)game_player_equip },
	{ "env_bubbles", (void*)env_bubbles },
	{ "game_team_set", (void*)game_team_set },
	{ "node_viewer", (void*)node_viewer },
	{ "trigger_autosave", (void*)trigger_autosave },
	{ "trigger_changetarget", (void*)trigger_changetarget },
	{ "entity_botcam", (void*)entity_botcam },
	{ "monster_houndeye", (void*)monster_houndeye },
	{ "controller_head_ball", (void*)controller_head_ball },
	{ "item_slave_collar", (void*)item_slave_collar },
	{ "env_explosion", (void*)env_explosion },
	{ "xen_ttrigger", (void*)xen_ttrigger },
	{ "path_track", (void*)path_track },
	{ "func_wall_toggle", (void*)func_wall_toggle },
	{ "momentary_rot_button", (void*)momentary_rot_button },
	{ "trigger_clientspawn", (void*)trigger_clientspawn },
	{ "node_viewer_human", (void*)node_viewer_human },
	{ "func_tracktrain", (void*)func_tracktrain },
	{ "controller_energy_ball", (void*)controller_energy_ball },
	{ "monster_zombie", (void*)monster_zombie },
	{ "monster_barnacle", (void*)monster_barnacle },
	{ "env_warpball", (void*)env_warpball },
	{ "trigger_multiple", (void*)trigger_multiple },
	{ "ammo_egonclip", (void*)ammo_egonclip },
	{ "trigger_endsection", (void*)trigger_endsection },
	{ "displacer_teleporter", (void*)displacer_teleporter },
	{ "func_friction", (void*)func_friction },
	{ "xen_hull", (void*)xen_hull },
	{ "env_spark", (void*)env_spark },
	{ "env_smoker", (void*)env_smoker },
	{ "env_glow", (void*)env_glow },
	{ "player", (void*)player },
	{ "target_cdaudio", (void*)target_cdaudio },
	{ "trigger_push", (void*)trigger_push },
	{ "game_team_master", (void*)game_team_master },
	{ "scripted_sentence", (void*)scripted_sentence },
	{ "laser_spot", (void*)laser_spot },
	{ "xen_spore_small", (void*)xen_spore_small },
	{ "monster_cockroach", (void*)monster_cockroach },
	{ "monster_tentaclemaw", (void*)monster_tentaclemaw },
	{ "path_corner", (void*)path_corner },
	{ "game_player_team", (void*)game_player_team },
	{ "func_mortar_field", (void*)func_mortar_field },
	{ "ammo_rpgclip", (void*)ammo_rpgclip },
	{ "info_displacer_earthdeastination", (void*)info_displacer_earthdeastination },
	{ "func_tank", (void*)func_tank },
	{ "func_tanklaser", (void*)func_tanklaser },
	{ "node_viewer_large", (void*)node_viewer_large },
	{ "info_landmark", (void*)info_landmark },
	{ "monster_ichthyosaur", (void*)monster_ichthyosaur },
	{ "info_node", (void*)info_node },
	{ "func_illusionary", (void*)func_illusionary },
	{ "trigger_new_hurt", (void*)trigger_new_hurt },
	{ "item_sodacan", (void*)item_sodacan },
	{ "ammo_357", (void*)ammo_357 },
	{ "item_longjump", (void*)item_longjump },
	{ "squidspit", (void*)squidspit },
	{ "ammo_mp5grenades", (void*)ammo_mp5grenades },
	{ "info_cheathelper", (void*)info_cheathelper },
	{ "ammo_crossbow", (void*)ammo_crossbow },
	{ "env_sprite", (void*)env_sprite },
	{ "item_antidote", (void*)item_antidote },
	{ "func_water", (void*)func_water },
	{ "item_suit", (void*)item_suit },
	{ "xen_spore_large", (void*)xen_spore_large },
	{ "monster_mortar", (void*)monster_mortar },
	{ "func_tankrocket", (void*)func_tankrocket },
	{ "node_viewer_fly", (void*)node_viewer_fly },
	{ "info_target", (void*)info_target },
	{ "info_null", (void*)info_null },
	{ "func_breakable", (void*)func_breakable },
	{ "monster_hevsuit_dead", (void*)monster_hevsuit_dead },
	{ "monster_headcrab", (void*)monster_headcrab },
	{ "func_wall", (void*)func_wall },
	{ "trigger_random", (void*)trigger_random },
	{ "trigger_autobot", (void*)trigger_autobot },
	{ "infodecal", (void*)infodecal },
	{ "func_monsterclip", (void*)func_monsterclip },
	{ "cycler_sprite", (void*)cycler_sprite },
	{ "weapon_python", (void*)weapon_python },
	{ "monster_tripmine", (void*)monster_tripmine },
	{ "monster_human_grunt", (void*)monster_human_grunt },
	{ "func_guntarget", (void*)func_guntarget },
	{ "env_elight", (void*)env_elight },
	{ "trigger_auto", (void*)trigger_auto },
	{ "hornet", (void*)hornet },
	{ "func_door", (void*)func_door },
	{ "scripted_sequence", (void*)scripted_sequence },
	{ "trigger_enddecay", (void*)trigger_enddecay },
	{ "world_items", (void*)world_items },
	{ "weapon_shotgun", (void*)weapon_shotgun },
	{ "ammo_gaussclip", (void*)ammo_gaussclip },
	{ "item_healthkit", (void*)item_healthkit },
	{ "ammo_mp5clip", (void*)ammo_mp5clip },
	{ "speaker", (void*)speaker },
	{ "ambient_generic", (void*)ambient_generic },
	{ "func_recharge", (void*)func_recharge },
	{ "weapon_satchel", (void*)weapon_satchel },
	{ "button_target", (void*)button_target },
	{ "trigger_playerfreeze", (void*)trigger_playerfreeze },
	{ "func_tankcontrols", (void*)func_tankcontrols },
	{ "aiscripted_sequence", (void*)aiscripted_sequence },
	{ "monster_sentry", (void*)monster_sentry },
	{ "weapon_9mmhandgun", (void*)weapon_9mmhandgun },
	{ "monster_apache", (void*)monster_apache },
	{ "trigger_once", (void*)trigger_once },
	{ "monster_cine2_hvyweapons", (void*)monster_cine2_hvyweapons },
	{ "ammo_9mmAR", (void*)ammo_9mmAR },
	{ "monster_alien_grunt", (void*)monster_alien_grunt },
	{ "weapon_357", (void*)weapon_357 },
	{ "func_train", (void*)func_train },
	{ "monster_leech", (void*)monster_leech },
	{ "info_player_start", (void*)info_player_start },
	{ "env_blood", (void*)env_blood },
	{ "crossbow_bolt", (void*)crossbow_bolt },
	{ "trigger_relay", (void*)trigger_relay },
	{ "env_laser", (void*)env_laser },
	{ "multi_manager", (void*)multi_manager },
	{ "monster_babycrab", (void*)monster_babycrab },
	{ "env_beverage", (void*)env_beverage },
	{ "beam", (void*)beam },
	{ "env_beam", (void*)env_beam },
	{ "env_shooter", (void*)env_shooter },
	{ "monster_osprey", (void*)monster_osprey },
	{ "light_environment", (void*)light_environment },
	{ "xen_plantlight", (void*)xen_plantlight },
	{ "game_text", (void*)game_text },
	{ "rpg_rocket", (void*)rpg_rocket },
	{ "item_recharge", (void*)item_recharge },
	{ "player_loadsaved", (void*)player_loadsaved },
	{ "monster_turret", (void*)monster_turret },
	{ "multisource", (void*)multisource },
	{ "weapon_vorti", (void*)weapon_vorti },
	{ "weapon_hornetgun", (void*)weapon_hornetgun },
	{ "grenade", (void*)grenade },
	{ "env_lasermirror", (void*)env_lasermirror },
	{ "weapon_crowbar", (void*)weapon_crowbar },
	{ "func_traincontrols", (void*)func_traincontrols },
	{ "player_weaponstrip", (void*)player_weaponstrip },
	{ "monster_player", (void*)monster_player },
	{ "monster_snark", (void*)monster_snark },
	{ "weapon_mp5", (void*)weapon_mp5 },
	{ "weapon_snark", (void*)weapon_snark },
	{ "monster_grunt_repel", (void*)monster_grunt_repel },
	{ "monster_cine3_scientist", (void*)monster_cine3_scientist },
	{ "cine_blood", (void*)cine_blood },
	{ "item_eyescanner", (void*)item_eyescanner },
	{ "ammo_9mmclip", (void*)ammo_9mmclip },
	{ "trigger_transition", (void*)trigger_transition },
	{ "fireanddie", (void*)fireanddie },
	{ "soundent", (void*)soundent },
	{ "cycler_prdroid", (void*)cycler_prdroid },
	{ "cycler_weapon", (void*)cycler_weapon },
	{ "trigger_bit_counter", (void*)trigger_bit_counter },
	{ "trigger_cdaudio", (void*)trigger_cdaudio },
	{ "game_player_hurt", (void*)game_player_hurt },
	{ "item_battery", (void*)item_battery },
	{ "env_shake", (void*)env_shake },
	{ "monster_cine_panther", (void*)monster_cine_panther },
	{ "ammo_ARgrenades", (void*)ammo_ARgrenades },
	{ "item_security", (void*)item_security },
	{ "weapon_glock", (void*)weapon_glock },
	{ "func_ladder", (void*)func_ladder },
	{ "monster_scientist_dead", (void*)monster_scientist_dead },
	{ "ammo_9mmbox", (void*)ammo_9mmbox },
	{ "trigger_lockedmission", (void*)trigger_lockedmission },

	{ NULL, NULL },
};

int switch_installdll_server( void )
{
	return dll_register( "server", switch_server_exports );
}

}